# Admin 서비스는 다른 서비스와 달리 여러 서비스의 yml 을 import 하는 방식을 사용한다.
# 그런데 spring 의 config. import 는 선언된 순서대로 현재 설정을 override 하는 방식이다.
# 따라서 마지막에 import 된 yml 이 모든 설정을 덮어 쓰는 문제가 있다.
# 이 문제를 해결하기 위해 다른 설정에서도 사용하고 있는 속성값은 override 에 따로 정의하고, override yml 파일을 맨 마지막에 import 하는 방식을 사용한다.

spring:
  application:
    name: "micro-admin"
  messages:
    basename: messages/**/messages
  servlet:
    multipart:
      enabled: true

platform:
  config:
    admin:
      view:
        login:
          theme: violet
      dashboard:
        board:
          alias: board_notice,board_suggest,board_prctc,board_order
    microservice:
      monolithic: true
      admin: true
      asset: false
      cms: false
      commerce-catalog: false
      commerce-order: false
      commerce-promotion: false
      customer: false
      event: false
      support: false
      tenant: true
    security:
      server: true
    datasource:
      data-per-services: false
      provider:
        atomikos:
          use: false
    provider:
      search: hibernate
      cache: redis
      elastic: true #spring data elastic search 를 사용할 때만 이 값을 활성화 한다.
      kafka: false
      mongo: false
    asset:
      view:
        domain: http://localhost:8110
eureka:
  instance:
    intance-id: micro-admin-intance
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/
    register-with-eureka: true
    fetch-registry: true


feign:
  client:
    config:
      default:
        loggerLevel: FULL

management:
  endpoints:
    web:
      exposure:
        include: "*"

vaadin:
  productionMode: true
  whitelisted-packages: io/rchemist/admin